name: Deploy Heroku

on:
  push:
    branches: [main]

    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: make test