name: Deploy Heroku

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: make test

  deploy:
    needs: test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
    
      - name: Deploy to Heroku
        run: make heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
